name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install
        
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Test backend
      working-directory: ./Backend
      run: |
        npm install
        node -e "require('./app.js')"
        
    - name: Deploy to production
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          bash /home/ubuntu/Brilldaddy/scripts/deploy.sh

    - name: Notify on failure
      if: failure()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Deployment failed. Rolling back..."
          if [ -d "/home/ubuntu/backup" ]; then
            rm -rf /home/ubuntu/Brilldaddy/*
            cp -r /home/ubuntu/backup/* /home/ubuntu/Brilldaddy/
            pm2 restart all
            sudo systemctl restart nginx
          fi